name: Conan Server Monitor

on:
  schedule:
    - cron: '*/2 * * * *'  # Every 2 minutes
  workflow_dispatch:  # Manual testing

jobs:
  check-server:
    runs-on: ubuntu-latest
    steps:
    - name: Check Server Status
      run: |
        echo "Pinging server IP 104.243.40.213..."
        
        if ping -c 3 -W 5 104.243.40.213 > /dev/null 2>&1; then
          echo "Server IP is responding"
          MESSAGE="🟢 **Conan Server IP is responding** (likely online)"
        else
          echo "Server IP is not responding"
          MESSAGE="🔴 **Conan Server IP is not responding** (likely offline)"
        fi
        
        echo "Sending: $MESSAGE"
        curl -X POST "https://discord.com/api/webhooks/905960918075195462/9duCW7H-cNXj6bGefVLhXmdjPSOvDyjuV0TF79PWHnQoCJc_cdqyb6isJNlRCkf3wgEa" \
          -H "Content-Type: application/json" \
          -d "{\"content\":\"$MESSAGE\"}"
        
        echo "Notification sent"
