name: Conan Server Monitor

on:
  schedule:
    - cron: '*/2 * * * *'  # Every 2 minutes
  workflow_dispatch:  # Manual testing

jobs:
  check-server:
    runs-on: ubuntu-latest
    steps:
    - name: Check Server Status
      run: |
        echo "Checking server via BattleMetrics API..."
        
        # Try using BattleMetrics to find the server
        response=$(curl -s --connect-timeout 15 "https://api.battlemetrics.com/servers?filter[game]=conanexiles&filter[search]=104.243.40.213:8033" || echo "error")
        
        echo "API response: $response"
        
        if echo "$response" | grep -q "104.243.40.213"; then
          echo "Server found and ONLINE"
          MESSAGE="🟢 **Conan Server is ONLINE**"
        else
          echo "Server not found or OFFLINE"
          MESSAGE="🔴 **Conan Server is OFFLINE**"
        fi
        
        echo "Sending: $MESSAGE"
        curl -X POST "https://discord.com/api/webhooks/905960918075195462/9duCW7H-cNXj6bGefVLhXmdjPSOvDyjuV0TF79PWHnQoCJc_cdqyb6isJNlRCkf3wgEa" \
          -H "Content-Type: application/json" \
          -d "{\"content\":\"$MESSAGE\"}"
        
        echo "Notification sent"
