name: Conan Server Monitor

on:
  schedule:
    - cron: '*/2 * * * *'  # Every 2 minutes
  workflow_dispatch:  # Manual testing

jobs:
  check-server:
    runs-on: ubuntu-latest
    steps:
    - name: Check Server Status
      run: |
        echo "Checking server 104.243.40.213:8033..."
        
        # Try a different connection method
        if curl -s --connect-timeout 10 telnet://104.243.40.213:8033 </dev/null; then
          echo "Server is ONLINE"
          MESSAGE="🟢 **Conan Server is ONLINE**"
        else
          echo "Server appears OFFLINE (or not responding to this check)"
          MESSAGE="🔴 **Conan Server is OFFLINE or not responding**"
        fi
        
        echo "Sending: $MESSAGE"
        curl -X POST "https://discord.com/api/webhooks/905960918075195462/9duCW7H-cNXj6bGefVLhXmdjPSOvDyjuV0TF79PWHnQoCJc_cdqyb6isJNlRCkf3wgEa" \
          -H "Content-Type: application/json" \
          -d "{\"content\":\"$MESSAGE\"}"
        
        echo "Notification sent"
