name: Conan Server Monitor

on:
  workflow_dispatch:  # Manual testing only for now

jobs:
  check-server:
    runs-on: ubuntu-latest
    steps:
    - name: Test Discord Webhook
      run: |
        echo "Testing webhook..."
        curl -X POST "${{ secrets.DISCORD_WEBHOOK }}" \
          -H "Content-Type: application/json" \
          -d '{"content":"🧪 **Test message from GitHub Actions**"}'
        echo "Test complete"
