name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Test Discord
      run: |
        echo "Testing webhook..."
        curl -X POST "https://discord.com/api/webhooks/905960918075195462/9duCW7H-cNXj6bGefVLhXmdjPSOvDyjuV0TF79PWHnQoCJc_cdqyb6isJNlRCkf3wgEa" \
          -H "Content-Type: application/json" \
          -d '{"content":"🧪 **Test from GitHub Actions**"}'
        echo "Done"
