name: Conan Server Monitor

on:
  schedule:
    - cron: '*/2 * * * *'  # Every 2 minutes
  workflow_dispatch:  # Manual testing

jobs:
  check-server:
    runs-on: ubuntu-latest
    steps:
    - name: Check Server Status
      run: |
        echo "Checking server 104.243.40.213:8033..."
        
        # Install nmap for better server detection
        sudo apt-get update && sudo apt-get install -y nmap
        
        # Check if port is open/responding
        if nmap -p 8033 -sU --host-timeout 10s 104.243.40.213 | grep -q "open"; then
          echo "Server is ONLINE"
          MESSAGE="🟢 **Conan Server is ONLINE**"
        elif nmap -p 8033 -sT --host-timeout 10s 104.243.40.213 | grep -q "open"; then
          echo "Server is ONLINE"
          MESSAGE="🟢 **Conan Server is ONLINE**"
        else
          echo "Server appears OFFLINE"
          MESSAGE="🔴 **Conan Server is OFFLINE**"
        fi
        
        echo "Sending: $MESSAGE"
        curl -X POST "https://discord.com/api/webhooks/905960918075195462/9duCW7H-cNXj6bGefVLhXmdjPSOvDyjuV0TF79PWHnQoCJc_cdqyb6isJNlRCkf3wgEa" \
          -H "Content-Type: application/json" \
          -d "{\"content\":\"$MESSAGE\"}"
